EVENT_TYPES = frozenset("""
PAGE_HIDDEN PAGE_VISIBLE WINDOW_BLUR WINDOW_FOCUS
FULLSCREEN_ENTERED FULLSCREEN_EXIT FULLSCREEN_UNAVAILABLE
CLIPBOARD_ATTEMPT
COPY_SHORTCUT PASTE_SHORTCUT DEVTOOLS_SHORTCUT PRINT_SHORTCUT CONTEXT_MENU_ATTEMPT
NETWORK_DISCONNECTED NETWORK_RECONNECTED HEARTBEAT_MISSED
CAMERA_PERMISSION_CHANGED MICROPHONE_PERMISSION_CHANGED
UNAUTHORIZED_PROCESS PROCESS_MONITOR_UNAVAILABLE
MULTIPLE_MONITOR DISPLAY_CONFIGURATION_CHANGED
PRINT_ATTEMPT SCREENSHOT_ATTEMPT
NATIVE_CLIENT_STARTED NATIVE_CRASH_RECOVERED
""".split())

CLIENT_SOURCES = frozenset({"WEB_CLIENT", "NATIVE_CLIENT"})  # SERVER/ADMIN client nahi bhej sakta
