<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>SafeExam.Client</RootNamespace>
    <AssemblyName>SafeExam.Client</AssemblyName>
    <StartupObject>SafeExam.Client.Program</StartupObject>
    <Version>1.0.0</Version>
    <InvariantGlobalization>true</InvariantGlobalization>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.2792.45" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.1" />
    <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="8.0.0" />
  </ItemGroup>
  <ItemGroup>
    <!-- Trusted public keys (private key kabhi yahan nahi) -->
    <EmbeddedResource Include="Security\trusted_keys.json" LogicalName="trusted_keys.json" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="SafeExam.Tests" />
  </ItemGroup>
</Project>
