"""a20 reviews

Revision ID: a005
Revises: a004
"""
from alembic import op
import sqlalchemy as sa


revision = 'a005'
down_revision = 'a004'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_assignments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('attempt_id', sa.String(length=36), nullable=False),
    sa.Column('reviewer_id', sa.String(length=36), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['exam_attempts.id'], name=op.f('fk_review_assignments_attempt_id_exam_attempts')),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], name=op.f('fk_review_assignments_reviewer_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review_assignments')),
    sa.UniqueConstraint('attempt_id', 'reviewer_id', name='uq_review_assignments_attempt_reviewer')
    )
    op.create_index(op.f('ix_review_assignments_attempt_id'), 'review_assignments', ['attempt_id'], unique=False)
    op.create_index(op.f('ix_review_assignments_reviewer_id'), 'review_assignments', ['reviewer_id'], unique=False)
    op.create_table('review_decisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('attempt_id', sa.String(length=36), nullable=False),
    sa.Column('reviewer_id', sa.String(length=36), nullable=False),
    sa.Column('decision', sa.String(length=30), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('is_appeal', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['exam_attempts.id'], name=op.f('fk_review_decisions_attempt_id_exam_attempts')),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], name=op.f('fk_review_decisions_reviewer_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review_decisions'))
    )
    op.create_index(op.f('ix_review_decisions_attempt_id'), 'review_decisions', ['attempt_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_decisions_attempt_id'), table_name='review_decisions')
    op.drop_table('review_decisions')
    op.drop_index(op.f('ix_review_assignments_reviewer_id'), table_name='review_assignments')
    op.drop_index(op.f('ix_review_assignments_attempt_id'), table_name='review_assignments')
    op.drop_table('review_assignments')
    # ### end Alembic commands ###
